import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

GEMINI_KEY = os.environ.get("GEMINI_API_KEY", "")
GROQ_KEY   = os.environ.get("GROQ_API_KEY", "")

PROMPT = """
You are a Senior Smart Contract and Agentic Flow Security Auditor.
You are reviewing a bug report generated by an automated test harness for the MultiHopper protocol (multi-hop token routing on Solana).

Below is the raw markdown bug report.
Please enrich the report by appending a new, professional security audit section titled:
"## Agentic & On-Chain Security Impact Analysis"

In this section:
1. Explain the deep smart contract and economic implications of the Critical and High findings (e.g., signature spoofing, TypeScript signature zeroing, concurrent blockhash race conditions).
2. Detail how an AI agent operating autonomously in production might get stuck, lose funds, or be exploited.
3. Suggest robust client-side and server-side mitigation strategies.

Keep the markdown structure clean and preserve all existing findings exactly as they are.

Raw Report:
{raw_report}
"""


def enrich_report(report_path: str = "reports/mh_bug_report.md", output_path: str = "reports/mh_bug_report_enriched.md") -> bool:
    if not os.path.exists(report_path):
        print(f"Error: {report_path} not found. Run harness.py first.")
        return False

    with open(report_path, "r", encoding="utf-8") as fh:
        raw_report = fh.read()

    enriched_content = ""

    if GEMINI_KEY:
        print("  [AI] Enriching report via Google GenAI SDK (Gemma 4)...")
        try:
            from google import genai
            client = genai.Client()
            response = client.models.generate_content(
                model="gemma-4-26b-a4b-it",
                contents=PROMPT.format(raw_report=raw_report)
            )
            response_text = response.text or ""
            enriched_content = raw_report + "\n\n" + response_text
        except ImportError:
            print("  [AI] google-genai SDK not found. Falling back to HTTP REST call (Gemma 4)...")
            import requests
            try:
                url = f"https://generativelanguage.googleapis.com/v1beta/models/gemma-4-26b-a4b-it:generateContent?key={GEMINI_KEY}"
                resp = requests.post(url, json={
                    "contents": [{"parts": [{"text": PROMPT.format(raw_report=raw_report)}]}]
                }, timeout=60)
                resp.raise_for_status()
                text = resp.json()["candidates"][0]["content"]["parts"][0]["text"]
                enriched_content = raw_report + "\n\n" + text
            except Exception as e:
                print(f"  [AI] Gemma 4 REST fallback failed: {e}")
        except Exception as e:
            print(f"  [AI] Google GenAI SDK failed: {e}")

    elif GROQ_KEY:
        print("  [AI] Enriching report via Groq API...")
        import requests
        try:
            url = "https://api.groq.com/openai/v1/chat/completions"
            resp = requests.post(url, headers={
                "Authorization": f"Bearer {GROQ_KEY}",
                "Content-Type": "application/json"
            }, json={
                "model": "llama-3.3-70b-versatile",
                "messages": [{"role": "user", "content": PROMPT.format(raw_report=raw_report)}],
                "temperature": 0.2
            }, timeout=60)
            resp.raise_for_status()
            text = resp.json()["choices"][0]["message"]["content"]
            enriched_content = raw_report + "\n\n" + text
        except Exception as e:
            print(f"  [AI] Groq API failed: {e}")

    else:
        print("  [AI] No LLM API keys set in .env. Skipping AI report enrichment.")
        return False

    if enriched_content:
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write(enriched_content)
        print(f"  [AI] Enriched report written to {output_path}")
        return True

    return False


if __name__ == "__main__":
    import dotenv
    dotenv.load_dotenv()
    enrich_report()
